health/urls.py
from django.urls import path
from . import views

app_name = 'health'
urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    #path('inquiry/', views.InquiryView.as_view(), name="inquiry"),
    #path('', views.HealthListView.as_view(), name="health_list"),
    path('health-detail/<int:pk>/', views.HealthDetailView.as_view(), name="health_detail"),
    path('health-create/', views.HealthCreateView.as_view(), name="health_create"),
    path('health-update/<int:pk>/', views.HealthUpdateView.as_view(), name="health_update"),
    path('health-delete/<int:pk>/', views.HealthDeleteView.as_view(), name="health_delete"),
]

private_health/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('', include('health.urls')),
    path('admin/', admin.site.urls),
]

health/models.py
from django.db import models
class Health(models.Model):
    morning_state = models.TextField(verbose_name='朝の症状', blank=True, null=True)
    morning_temperature = models.IntegerField(verbose_name='朝の体温', blank=True, null=True)
    night_state = models.TextField(verbose_name='夜の症状', blank=True, null=True)
    night_temperature = models.IntegerField(verbose_name='夜の体温', blank=True, null=True)
    note = models.TextField(verbose_name='備考', blank=True, null=True)
    niti = models.DateTimeField(verbose_name='作成日時',blank=True,null=True,auto_now_add=True)


    class Meta:
        verbose_name_plural = 'health'

    def __str__(self):
        return self.title

health/forms.py
import os
from .models import Health
from django import forms

class HealthCreateForm(forms.ModelForm):
    class Meta:
        model = Health
        fields = ("morning_state","morning_temperature","night_state","night_temperature","note",)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

health/views.py
from django.shortcuts import render
from django.views import generic

from .forms import HealthCreateForm
from .models import Health
from django.urls import reverse_lazy
from django.contrib import messages

class IndexView(generic.ListView):
    model = Health
    template_name = 'index.html'

class HealthCreateView(generic.CreateView):
    model = Health
    template_name = 'health_create.html'
    form_class = HealthCreateForm
    success_url = reverse_lazy('health:index')

    def form_valid(self, form):
        health = form.save(commit=False)
        health.save()
        messages.success(self.request, '登録しました。')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "登録に失敗しました。")
        return super().form_invalid(form)

class HealthDetailView(generic.DetailView):
    model = Health
    template_name = 'health_detail.html'

class HealthUpdateView(generic.UpdateView):
    model = Health
    template_name = 'health_update.html'
    form_class = HealthCreateForm

    def get_success_url(self):
        return reverse_lazy('health:health_detail', kwargs={'pk': self.kwargs['pk']})

    def form_valid(self, form):
        messages.success(self.request, '更新しました。')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.success(self.request, '更新しました。')
        return super().form_invalid(form)

class HealthDeleteView(generic.DeleteView):
    model = Health
    template_name = 'health_delete.html'
    success_url = reverse_lazy('health:index')

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, "削除しました。")
        return super().delete(request, *args, **kwargs)

health/templates/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

health/templates/health_create.html
<!DOCTYPE html>
<html lang="ja">
<html>
<head>
    <meta charset="UTF-8">
    <title>健康状態登録画面</title>
</head>
<body>
    <h1>健康状態登録</h1>
    <form method="POST">
        {% csrf_token %}
            <table class="table">
                {{ form.as_table }}
            </table>
            <button class="btn btn-primary" type="submit">作成</button>
            <a class="btn btn-secondary mt-5 ml-2" href="{% url 'health:index' %}" >戻る</a>
        </form>
</body>
</html>

health/templates/health_delete.html
<!DOCTYPE html>
<html lang="ja">

<div style="padding: 10px; margin-bottom: 10px; border: 1px solid #333333;">
<head>
    <meta charset="UTF-8">
    <title>健康状態削除確認画面</title>
    <p>健康状態削除確認</p>
    <style> .box{border: solid 3px #000}</style>

</head>
<body>
<form method="POST">
    <p><font size=5>本当に削除しますか？</font></p>
    {% csrf_token %}
    <button class="btn btn-primary mt-5" type="submit">削除</button>
</form>


<br><br><button><a class="btn btn-secondary mt-5 ml-2" href="{% url 'health:health_detail' health.pk %}">キャンセル</a></button>
</body>
</div>

</html>

health/templates/health_detail.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>健康状態詳細画面</title>
</head>
<body>
<h1>健康状態詳細</h1>
<div class="container my-div-style">
    <div class="row">
        <div class="col-3">
            <strong>作成日時</strong>
        </div>
        <div class="col-9">
            {{ object.niti }}
        </div>

        <hr>

    <div class="row">
        <div class="col-3">
            <strong>朝の症状</strong>
        </div>
        <div class="col-9">
            {{ object.morning_state }}
        </div>
    </div>

    <hr>

    <div class="row">
        <div class="col-3">
            <strong>朝の体温</strong>
        </div>
        <div class="col-9">
            {{ object.morning_temperature }}
        </div>
    </div>

    <hr>

    <div class="row">
        <div class="col-3">
            <strong>夜の症状</strong>
        </div>
        <div class="col-9">
            {{ object.night_state }}
        </div>
    </div>

    <hr>

    <div class="row">
        <div class="col-3">
            <strong>夜の体温</strong>
        </div>
        <div class="col-9">
            {{ object.night_temperature }}
        </div>
    </div>

    <hr>

    <div class="row">
        <div class="col-3">
            <strong>備考</strong>
        </div>
        <div class="col-9" style="word-wrap: break-word;">
            {{ object.note }}
        </div>
    </div>
</div>
<a class="btn btn-secondary mt-5 ml-2" href="{% url 'health:health_update' health.pk %}">修正</a>
<a class="btn btn-secondary mt-5 ml-2" href="{% url 'health:health_delete' health.pk %}">削除</a>
<button onclick="location.href='{% url 'health:index' %}'">戻る</button>
</body>
</html>

health/templates/health_update.html
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>健康状態詳細画面</title>
</head>
<body>
<h1>健康状態登録</h1>
<form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
            <table class="table">
                {{ form.as_table }}
            </table>
        <p><input type="submit" value="修正" ></p>
        <p><input type="button" value="戻る" onClick="javascript:history.go(-1);"></p>
</form>
</body>
</html>

health/templates/index.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>健康状態一覧画面</title>
</head>
<body>
<h1>健康状態一覧</h1>
<div class="post-preview">
    <table border="2">
                {% if health_list %}
                <tr>
                    <th>記録日時</th>
                    <th>朝の症状</th>
                    <th>夜の症状</th>
                </tr>
                {% for health in health_list %}
                <tr>
                    <td><a href="{% url 'health:health_detail' health.pk %}">{{ health.niti }}</a></td>
                    <td><a href="{% url 'health:health_detail' health.pk %}">{{ health.morning_state }}</a></td>
                    <td><a href="{% url 'health:health_detail' health.pk %}">{{ health.night_state}}</a></td>
                </tr>
                {% endfor %}
                {% else %}
                <p>記録がありません。</p>
                {% endif %}

            </table>
    {% for health in object_list %}

    {% empty %}
    {% endfor %}
</div>



<a class="btn btn-primary" href="{% url 'health:health_create' %}">新規登録</a>
</body>
</html>